-- Distinguish direct plan grants from the compatibility row created to make an
-- item-assigned reporter discover the plan. Without this provenance, access to
-- one item implicitly authorized every item/evidence in the plan.
ALTER TABLE "pma_plan_assignments"
  ADD COLUMN IF NOT EXISTS "explicit_access" boolean DEFAULT true NOT NULL;
--> statement-breakpoint
ALTER TABLE "rgdp_plan_assignments"
  ADD COLUMN IF NOT EXISTS "explicit_access" boolean DEFAULT true NOT NULL;
--> statement-breakpoint

-- Historical REPORTER rows accompanied by an item assignment were generated by
-- the old direction assignment flow. Classify them as derived. VIEWER grants
-- remain explicit because viewers are assigned at plan level by design.
UPDATE "pma_plan_assignments" AS pa
SET "explicit_access" = false
WHERE EXISTS (
  SELECT 1
  FROM "users" AS u
  JOIN "pma_item_assignments" AS ia ON ia."user_id" = u."id"
  JOIN "pma_plan_items" AS pi ON pi."id" = ia."plan_item_id"
  WHERE u."id" = pa."user_id"
    AND u."role" = 'REPORTER'
    AND pi."plan_id" = pa."plan_id"
);
--> statement-breakpoint
UPDATE "rgdp_plan_assignments" AS pa
SET "explicit_access" = false
WHERE EXISTS (
  SELECT 1
  FROM "users" AS u
  JOIN "rgdp_item_assignments" AS ia ON ia."user_id" = u."id"
  JOIN "rgdp_plan_items" AS pi ON pi."id" = ia."plan_item_id"
  WHERE u."id" = pa."user_id"
    AND u."role" = 'REPORTER'
    AND pi."plan_id" = pa."plan_id"
);
